language: node_js # 声明环境为node
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存node_modules文件夹

# S: Build Lifecycle
install:
  - npm install # 下载依赖g

# script:
#   - hexo g # 我装了algolia的搜索工具。这一步正常可以是 hexo g

script:
- hexo clean
- hexo generate
# 执行的成功后执行 

after_success:
- hexo deploy

after_script: # 推送到github的部分
  - cd ./public
  - git init
  - git config user.name "willwang1997"
  - git config user.email "942345396@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # 通过之前存在Travis-CI里的token以及github仓库的地址推送到相应的master分支
   # Coding Pages
  - git push --force --quiet "https://${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --quiet "https://${CO_TOKEN}@${CO_REF}" master:master --tags
# E: Build LifeCycle

branches:
  only:
    - hexo # 只对hexo分支构建

env: # 环境变量
 global:
   - GH_REF: github.com/willwang1997/willwang1997.github.io.git # 我的仓库地址
   # Coding Pages
   - CO_REF: e.coding.net/wangwei1997/wangwei/wangwei.git